// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

//const SUPABASE_URL = "https://vmihkigligqwsauzryvf.supabase.co";
//const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtaWhraWdsaWdxd3NhdXpyeXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTQ5OTksImV4cCI6MjA3MzI3MDk5OX0.5Csjmdy6jE__fZ1wJHTKvbFqNDJeD50L13lrl7MFCBo";

const SUPABASE_URL = "https://supabase.ppfsui.com:8443";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS5wcGZzdWkuY29tIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk5OTA4NDgwMH0.2pR7L3sT5dQ8fG7hJ2kM9jN0lP1oQ3rS4tU5vW6xY7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
